apiVersion: v1
kind: Pod
metadata: 
  name: stress-pod
  labels: 
    env: dev
spec:
  containers:
    - name: stress-co
      image: progrium/stress
      ports:
        - containerPort: 80
          protocol: TCP 
      command: ["stress", "--vm", "2", "--vm-bytes", "125M"]    
      resources: 
        requests:
          cpu: 150m
          memory: 100Mi
        limits:
          cpu: 200m
          memory: 150Mi      